<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hasilcetakkk_model extends CI_Model
{

    public $table = 'hasilcetakkk';
    public $id = 'id_hasilcetakkk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_hasilcetakkk,nik,nokk,nama,alamat,kecamatan,desalurah,tgl_cetak,nama_register,nama_operator,status_cetak,alasan_cetak,nama_pengurus,ket,catatan');
        $this->datatables->from('hasilcetakkk');
        //add this line for join
        //$this->datatables->join('table2', 'hasilcetakkk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('hasilcetakkk/read/$1'),'<i class="fa fa-search"></i>', 'class="btn btn-xs btn-primary"  data-toggle="tooltip" title="Detail"')."  ".anchor(site_url('hasilcetakkk/update/$1'),'<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"')."  ".anchor(site_url('hasilcetakkk/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'hasilcetakkk/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id_hasilcetakkk');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_hasilcetakkk', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nokk', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('desalurah', $q);
	$this->db->or_like('tgl_cetak', $q);
	$this->db->or_like('nama_register', $q);
	$this->db->or_like('nama_operator', $q);
	$this->db->or_like('status_cetak', $q);
	$this->db->or_like('alasan_cetak', $q);
	$this->db->or_like('nama_pengurus', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('catatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_hasilcetakkk', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nokk', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('desalurah', $q);
	$this->db->or_like('tgl_cetak', $q);
	$this->db->or_like('nama_register', $q);
	$this->db->or_like('nama_operator', $q);
	$this->db->or_like('status_cetak', $q);
	$this->db->or_like('alasan_cetak', $q);
	$this->db->or_like('nama_pengurus', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('catatan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }


}

/* End of file Hasilcetakkk_model.php */
/* Location: ./application/models/Hasilcetakkk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-19 06:36:57 */
/* http://harviacode.com */