<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hasilregisterkonsolidasi_model extends CI_Model
{

    public $table = 'hasilregisterkonsolidasi';
    public $id = 'id_konsolidasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_konsolidasi,no_id,nik,nama_lengkap,no_kk,kabkota,kecamatan,desalurah,permasalahan,status_dwh,tgl_register,nama_register,nama_resepsionis,nama_pengguna,keterangan');
        $this->datatables->from('hasilregisterkonsolidasi');
        //add this line for join
        //$this->datatables->join('table2', 'hasilregisterkonsolidasi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('hasilregisterkonsolidasi/read/$1'),'<i class="fa fa-search"></i>', 'class="btn btn-xs btn-primary"  data-toggle="tooltip" title="Detail"')."  ".anchor(site_url('hasilregisterkonsolidasi/update/$1'),'<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"')."  ".anchor(site_url('hasilregisterkonsolidasi/delete/$1'),'<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'hasilregisterkonsolidasi/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id_konsolidasi');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_konsolidasi', $q);
	$this->db->or_like('no_id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('kabkota', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('desalurah', $q);
	$this->db->or_like('permasalahan', $q);
	$this->db->or_like('status_dwh', $q);
	$this->db->or_like('tgl_register', $q);
	$this->db->or_like('nama_register', $q);
	$this->db->or_like('nama_resepsionis', $q);
	$this->db->or_like('nama_pengguna', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_konsolidasi', $q);
	$this->db->or_like('no_id', $q);
	$this->db->or_like('nik', $q);
	$this->db->or_like('nama_lengkap', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('kabkota', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('desalurah', $q);
	$this->db->or_like('permasalahan', $q);
	$this->db->or_like('status_dwh', $q);
	$this->db->or_like('tgl_register', $q);
	$this->db->or_like('nama_register', $q);
	$this->db->or_like('nama_resepsionis', $q);
	$this->db->or_like('nama_pengguna', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }


}

/* End of file Hasilregisterkonsolidasi_model.php */
/* Location: ./application/models/Hasilregisterkonsolidasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-12-21 01:11:27 */
/* http://harviacode.com */